[Service]
# DSI-1 als Output fixieren, transient-seat für korrekte Eingabe-Mapping
ExecStart=
ExecStart=/usr/bin/rpi-connect-env /usr/bin/wayvnc --config /etc/rpi-connect/wayvnc.config --render-cursor --unix-socket --transient-seat -o DSI-1 --socket=%t/rpi-connect-wayvnc-ctl.sock %t/rpi-connect-wayvnc.sock
