[Service]
# DSI-1 fixieren, transient-seat entfernt (gab 2 Mauszeiger + kein Klick)
ExecStart=
ExecStart=/usr/bin/rpi-connect-env /usr/bin/wayvnc --config /etc/rpi-connect/wayvnc.config --unix-socket -o DSI-1 --socket=%t/rpi-connect-wayvnc-ctl.sock %t/rpi-connect-wayvnc.sock
